# Generated by Django 3.2.5 on 2022-05-14 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200, unique=True)),
                ('max_age', models.IntegerField()),
                ('min_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassOfSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassId', models.CharField(max_length=200)),
                ('max_number', models.IntegerField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMan.age')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectID', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('approved_mark', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherID', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('dateOfBirth', models.DateTimeField()),
                ('sex', models.CharField(choices=[('nam', 'nam'), ('nu', 'nu')], max_length=200, null=True)),
                ('ClassOfSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMan.classofschool')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMan.subject')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMan.account')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMan.age')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('dateOfBirth', models.DateTimeField()),
                ('sex', models.CharField(choices=[('nam', 'nam'), ('nu', 'nu')], max_length=200, null=True)),
                ('ClassOfSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMan.classofschool')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMan.account')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMan.age')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_mark', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200)),
                ('markFifteen', models.FloatField()),
                ('markFinal', models.FloatField()),
                ('markOne', models.FloatField()),
                ('StudentID_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_mark', to='studentMan.student')),
                ('SubjectID_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMan.subject')),
                ('year_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_mark', to='studentMan.student')),
            ],
        ),
    ]
