# Generated by Django 4.0.3 on 2022-06-08 02:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentMan.subject'),
        ),
        migrations.AlterField(
            model_name='classofschool',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='studentMan.age'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dateOfBirth',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 0, 0)),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentMan.student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='studentMan.subject'),
        ),
    ]
