# Generated by Django 4.0.3 on 2022-05-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dateOfBirth',
            field=models.DateTimeField(null=True),
        ),
    ]
