# Generated by Django 4.0.3 on 2022-06-09 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0002_subject_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dateOfBirth',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 0, 0)),
        ),
    ]
