# Generated by Django 4.0.3 on 2022-05-24 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0003_alter_teacher_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMan.account', unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMan.account', unique=True),
        ),
    ]
