# Generated by Django 4.0.3 on 2022-06-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0003_choices_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
