# Generated by Django 4.0.3 on 2022-05-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0004_alter_student_username_alter_teacher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentMan.account'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentMan.account'),
        ),
    ]
