# Generated by Django 4.0.3 on 2022-06-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0005_choices_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classOfSchool',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classOfSchool',
            field=models.ManyToManyField(blank=True, to='studentMan.classofschool'),
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
