# Generated by Django 4.0.3 on 2022-06-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0006_remove_profile_choices_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='semester_mark',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=200),
        ),
    ]
