# Generated by Django 4.0.3 on 2022-05-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0006_remove_student_username_remove_teacher_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('nam', 'nam'), ('nu', 'nữ')], max_length=200, null=True),
        ),
    ]
