# Generated by Django 4.0.3 on 2022-05-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0008_student_address_teacher_address_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='markFifteen',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='markFinal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='markOne',
            field=models.FloatField(null=True),
        ),
    ]
