# Generated by Django 4.0.3 on 2022-05-25 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0009_alter_mark_markfifteen_alter_mark_markfinal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ClassOfSchool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentMan.classofschool'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='ClassOfSchool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentMan.classofschool'),
        ),
    ]
