# Generated by Django 4.0.3 on 2022-05-25 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0010_alter_student_classofschool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='SubjectID_mark',
            new_name='Subject',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='StudentID_mark',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='year_mark',
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentMan.student'),
        ),
    ]
