# Generated by Django 4.0.3 on 2022-06-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0010_alter_student_address_alter_student_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='markFifteen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='markFinal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='markOne',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(blank=True, choices=[('nam', 'nam'), ('nu', 'nu')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(blank=True, choices=[('nam', 'nam'), ('nu', 'nữ')], max_length=200, null=True),
        ),
    ]
