# Generated by Django 4.0.3 on 2022-06-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0011_alter_mark_markfifteen_alter_mark_markfinal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classofschool',
            old_name='ClassId',
            new_name='classId',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='StudentID_mark',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='SubjectID_mark',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='year_mark',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ClassOfSchool',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='ClassOfSchool',
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentMan.student'),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentMan.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='classOfSchool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentMan.classofschool'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classOfSchool',
            field=models.ManyToManyField(blank=True, to='studentMan.classofschool'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='semester_mark',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('nam', 'nam'), ('nu', 'nu')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('nam', 'nam'), ('nu', 'nữ')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentMan.subject'),
        ),
    ]
