# Generated by Django 3.2.5 on 2022-05-31 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentMan', '0012_rename_classid_classofschool_classid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='markFifteen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='markFinal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='markOne',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentMan.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classOfSchool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentMan.classofschool'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classOfSchool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentMan.classofschool'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentMan.subject'),
        ),
    ]
